name: Publish Package

on:
  push:
    branches: [main]
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Create .npmrc (explicit)
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" > ~/.npmrc
          echo "@rprojects:registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "always-auth=true" >> ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Kök paketin node bağımlılıkları gerekli değilse bunu bile atlayabilirsiniz
      - name: Install deps (optional)
        run: npm ci || npm install

      - name: Build WASM (bundler)
        run: wasm-pack build --target bundler --out-dir pkg --scope rprojects --release

      - name: Show contents to be published
        run: |
          ls -la pkg
          npm pack ./pkg --dry-run

      - name: Publish ./pkg to NPM
        run: npm publish ./pkg --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
